import { Trophy, Code, Github, Target, Zap } from 'lucide-react';

const MOTIVATION_QUOTES = [
  "The expert in anything was once a beginner. - Helen Hayes",
  "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
  "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "It always seems impossible until it’s done. - Nelson Mandela",
  "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
  "Dream big and dare to fail. - Norman Vaughan",
  "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Don’t let yesterday take up too much of today. - Will Rogers",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Believe you can and you’re halfway there. - Theodore Roosevelt",
  "Act as if what you do makes a difference. It does. - William James",
  "Quality is not an act, it is a habit. - Aristotle",
  "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
  "The secret of getting ahead is getting started. - Mark Twain",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "If you can dream it, you can do it. - Walt Disney",
  "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "The best way to get started is to quit talking and begin doing. - Walt Disney",
  "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success is not in what you have, but who you are. - Bo Bennett",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "Doubt kills more dreams than failure ever will. - Suzy Kassem",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "You miss 100% of the shots you don’t take. - Wayne Gretzky",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
  "The best revenge is massive success. - Frank Sinatra",
  "The difference between ordinary and extraordinary is that little extra.",
  "Don’t limit your challenges. Challenge your limits.",
  "Difficult roads often lead to beautiful destinations.",
  "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
  "The harder the battle, the sweeter the victory.",
  "If you’re going through hell, keep going. - Winston Churchill",
  "You don’t have to see the whole staircase, just take the first step. - Martin Luther King Jr.",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Opportunities are usually disguised as hard work, so most people don’t recognize them. - Ann Landers",
  "Don’t count the days, make the days count. - Muhammad Ali",
  "The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.",
  "You are capable of amazing things.",
  "Success is not for the lazy.",
  "You don’t need to be perfect to be amazing.",
  "Be stronger than your excuses.",
  "You are your only limit.",
  "Stay positive, work hard, make it happen.",
  "Doubt kills more dreams than failure ever will.",
  "Don’t wish for it. Work for it.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Push yourself because no one else is going to do it for you.",
  "Don’t stop until you’re proud.",
  "Difficult doesn’t mean impossible.",
  "The struggle you’re in today is developing the strength you need for tomorrow.",
  "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
  "If you want something you’ve never had, you must be willing to do something you’ve never done. - Thomas Jefferson",
  "Don’t let what you cannot do interfere with what you can do. - John Wooden",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "You are never too old to set another goal or to dream a new dream. - Les Brown",
  "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Don’t be afraid to fail. Be afraid not to try.",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "The best way to predict the future is to create it. - Peter Drucker",
  "You can’t cross the sea merely by standing and staring at the water. - Rabindranath Tagore",
  "If you fell down yesterday, stand up today. - H.G. Wells",
  "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
  "Don’t let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
  "If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success. - John D. Rockefeller",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Don’t let yesterday take up too much of today. - Will Rogers",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "If you can’t fly then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do you have to keep moving forward. - Martin Luther King Jr.",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "You are confined only by the walls you build yourself.",
  "The best way out is always through. - Robert Frost",
  "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
  "If you want to make your dreams come true, the first thing you have to do is wake up. - J.M. Power",
  "The only thing that overcomes hard luck is hard work. - Harry Golden",
  "The difference between who you are and who you want to be is what you do.",
  "Don’t let small minds convince you that your dreams are too big.",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "You are capable of more than you know.",
  "Don’t be afraid to start over. It’s a chance to build something better this time.",
  "You don’t have to be perfect to be amazing.",
  "The only way to finish is to start.",
  "If you want to be the best, you have to do things other people aren’t willing to do.",
  "Don’t let the fear of striking out hold you back. - Babe Ruth",
  "If you want to go fast, go alone. If you want to go far, go together. - African Proverb",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
  "You are stronger than you think.",
  "Don’t let what you cannot do interfere with what you can do. - John Wooden",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "You are never too old to set another goal or to dream a new dream. - Les Brown",
  "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer"
];

const getTodaysQuote = () => {
  const day = Math.floor(Date.now() / (1000 * 60 * 60 * 24));
  return MOTIVATION_QUOTES[day % MOTIVATION_QUOTES.length];
};

const OverviewSection = ({ darkMode, goals, leetcodeStats, codeforcesStats, githubStats }) => (
  <div className="space-y-4">
    <h3 className={`text-lg font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>Your Coding Stats</h3>
    <div className="grid grid-cols-2 gap-4">
      <div className={`p-4 rounded-lg ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}> <div className="flex items-center space-x-2"> <Trophy className="w-5 h-5 text-yellow-500" /> <div> <div className="text-xl font-bold">{leetcodeStats?.totalSolved ?? '—'}</div> <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>LeetCode Solved</div> </div> </div> </div>
      <div className={`p-4 rounded-lg ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}> <div className="flex items-center space-x-2"> <Code className="w-5 h-5 text-purple-500" /> <div> <div className="text-xl font-bold">{codeforcesStats?.rating ?? '—'}</div> <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>Codeforces Rating</div> </div> </div> </div>
      <div className={`p-4 rounded-lg ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}> <div className="flex items-center space-x-2"> <Github className="w-5 h-5" /> <div> <div className="text-xl font-bold">{githubStats?.totalCommits ?? '—'}</div> <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>Total Commits</div> </div> </div> </div>
      <div className={`p-4 rounded-lg ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}> <div className="flex items-center space-x-2"> <Target className="w-5 h-5 text-blue-500" /> <div> <div className="text-xl font-bold">{goals.filter(g => g.completed).length}/{goals.length}</div> <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>Goals Completed</div> </div> </div> </div>
    </div>
    <div className={`p-4 rounded-lg ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}> <div className="flex items-center space-x-3"> <Zap className="w-5 h-5 text-yellow-500" /> <div> <h4 className={`font-medium ${darkMode ? 'text-white' : 'text-gray-900'}`}>Daily Motivation</h4> <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>{getTodaysQuote()}</p> </div> </div> </div>
  </div>
);

export default OverviewSection; 